add alias for non-existing ns
gfredericks/schpec pull request #13
Opened 2016-09-12 21:38 UTC by madstap

2016-09-16 00:25 UTC, gfredericks commented on src/com/gfredericks/schpec.clj
> +          (do (create-ns ~namespace-sym)
the `do` here is redundant -- `catch` can already take multiple expressions

2016-09-16 00:27 UTC, gfredericks commented on test/com/gfredericks/test_schpec.clj
> +  (let [aliases (ns-aliases 'com.gfredericks.test-schpec)]
this makes me wonder if it's possible to register an alias at a lower level without having to create the namespace? That might be good for tools that enumerate through all the namespaces and might get confused

2016-09-27 23:05 UTC, gfredericks commented on test/com/gfredericks/test_schpec.clj
> +  (let [aliases (ns-aliases 'com.gfredericks.test-schpec)]
it looks like there's no reasonably way of doing that

2016-09-27 23:06 UTC, gfredericks requested changes
this should be good to merge after this change

2016-09-27 23:06 UTC, gfredericks commented on src/com/gfredericks/schpec.clj
> +          (clojure.core/alias ~alias ~namespace-sym))))
Is there any need for this to be a macro? If not I'd rather keep it as a function to match the signature of `clojure.core/alias`.

2016-09-28 00:31 UTC, madstap commented on src/com/gfredericks/schpec.clj
> +          (clojure.core/alias ~alias ~namespace-sym))))
Yes, of course. For some reason I thought `clojure.core/alias` was a macro...

2016-09-28 00:49 UTC, gfredericks approved these changes

2016-09-28 01:36 UTC, merged

2016-09-28 01:36 UTC, gfredericks commented
this is great, thanks!

2016-09-28 01:45 UTC, gfredericks commented
Released in 0.1.1.